### ISSUE TITLE
AttributeError: 'module' object has no attribute 'path'

### ISSUE THREAD

**Issue by geekvc** [farrajota/fastrcnn-example-torch#1]
hello farrajota,
I am studying the fastrcnn, and very interested to you fastrcnn-example-torch repo.
I follow the readme, however get the error:
```sh
$ th train.lua
==> (1/5) Load options
==> (2/5) Load dataset data loader
==> (3/5) Load roi proposals data
==> (4/5) Setup model:
==> (5/5) Train Fast-RCNN model
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/dbcollection/manager.py", line 313, in config_cache
    cache_manager = CacheManager(is_test)
  File "/usr/local/lib/python2.7/dist-packages/dbcollection/utils/cache.py", line 26, in __init__
    self.setup_paths(is_test)
  File "/usr/local/lib/python2.7/dist-packages/dbcollection/utils/cache.py", line 60, in setup_paths
    home_dir = os.path.expanduser("~")
AttributeError: 'module' object has no attribute 'path'
/home/wangty/torch/install/bin/luajit: /home/wangty/torch/install/share/lua/5.1/json/init.lua:40: attempt to index local 'f' (a nil value)
stack traceback:
        /home/wangty/torch/install/share/lua/5.1/json/init.lua:40: in function 'load'
        ...gty/torch/install/share/lua/5.1/dbcollection/manager.lua:129: in function 'load'
        /mnt/geekvc/fastrcnn-example-torch/data.lua:13: in function 'get_db_loader'
        /mnt/geekvc/fastrcnn-example-torch/data.lua:34: in function 'fetch_loader_dataset'
        /mnt/geekvc/fastrcnn-example-torch/data.lua:298: in function 'data_gen'
        /home/wangty/torch/install/share/lua/5.1/fastrcnn/train.lua:47: in function 'train'
        train.lua:66: in main chunk
        [C]: in function 'dofile'
        ...ngty/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00406620

```
is it the dbcollection installation case the error?
Thank you in advance!

**Comment by farrajota** [comment]
Since the problem was due to the `dbcollection` package, I'll close this issue for now.

If you find any other problem related to the `fastrcnn` package please open a new issue.

**Comment by geekvc** [comment]
Though the dbcollection is installed correctly, this error still occur, I do not know how to solve it
```sh
$ th train.lua
==> (1/5) Load options
==> (2/5) Load dataset data loader
==> (3/5) Load roi proposals data
==> (4/5) Setup model:
==> (5/5) Train Fast-RCNN model
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/dbcollection/manager.py", line 46, in download
    cache_manager = CacheManager(is_test)
  File "/usr/local/lib/python2.7/dist-packages/dbcollection/utils/cache.py", line 26, in __init__
    self.setup_paths(is_test)
  File "/usr/local/lib/python2.7/dist-packages/dbcollection/utils/cache.py", line 60, in setup_paths
    home_dir = os.path.expanduser("~")
AttributeError: 'module' object has no attribute 'path'
/home/wangty/torch/install/bin/luajit: ...gty/torch/install/share/lua/5.1/dbcollection/manager.lua:58: attempt to index a nil value
stack traceback:
        ...gty/torch/install/share/lua/5.1/dbcollection/manager.lua:58: in function 'exists_task'
        ...gty/torch/install/share/lua/5.1/dbcollection/manager.lua:139: in function 'load'
        /mnt/geekvc/fastrcnn-example-torch/data.lua:13: in function 'get_db_loader'
        /mnt/geekvc/fastrcnn-example-torch/data.lua:34: in function 'fetch_loader_dataset'
        /mnt/geekvc/fastrcnn-example-torch/data.lua:298: in function 'data_gen'
        /home/wangty/torch/install/share/lua/5.1/fastrcnn/train.lua:47: in function 'train'
        train.lua:66: in main chunk
        [C]: in function 'dofile'
        ...ngty/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00406620
```
